/**
 * Lint Guard: the Recovery Kit's tool is in the Docker image.
 *
 * The kit is assembled at download time by reading the tool off disk. When it is not
 * there the request still succeeds - the zip is built with a placeholder text file
 * apologising for its absence. So a Dockerfile that forgets to copy it produces a broken
 * kit that looks fine, and the user finds out during a disaster.
 *
 * That is exactly what happened: the Dockerfile copied only `decrypt_backup.js` and never
 * `restore_archive.js`, so for as long as file backups existed, every kit generated by the
 * published image shipped an ERROR_MISSING file instead of the tool that reads them.
 *
 * Run with: pnpm test tests/unit/lint-guards/recovery-kit-shipped.test.ts
 */

import { describe, it, expect } from "vitest";
import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "../../..");

/** Script filenames the recovery kit service loads from disk at runtime. */
function scriptsReadAtRuntime(): string[] {
    const source = fs.readFileSync(path.join(ROOT, "src/services/backup/recovery-kit.ts"), "utf-8");
    return [...source.matchAll(/^export const RECOVERY_TOOL = "([^"]+)"/gm)].map((m) => m[1]);
}

describe("lint guard: recovery kit ships its tool", () => {
    const scripts = scriptsReadAtRuntime();

    it("knows which scripts the kit needs", () => {
        // A rename that this guard cannot follow must fail loudly rather than pass vacuously.
        expect(scripts.length).toBeGreaterThan(0);
    });

    it.each(scripts)("has %s in the repository", (script) => {
        expect(fs.existsSync(path.join(ROOT, "scripts", script))).toBe(true);
    });

    it.each(scripts)("copies %s into the runner image", (script) => {
        const dockerfile = fs.readFileSync(path.join(ROOT, "Dockerfile"), "utf-8");
        expect(dockerfile).toContain(`/app/scripts/${script}`);
    });

    it("does not still copy scripts that no longer exist", () => {
        const dockerfile = fs.readFileSync(path.join(ROOT, "Dockerfile"), "utf-8");
        for (const match of dockerfile.matchAll(/\/app\/scripts\/([\w.-]+)/g)) {
            expect(
                fs.existsSync(path.join(ROOT, "scripts", match[1])),
                `Dockerfile copies scripts/${match[1]}, which is not in the repository`
            ).toBe(true);
        }
    });
});
